using SharedServices.Models.Achievement;

namespace VO2DataManager.Web.Achievements;

public static class VO2Achievements
{
    public static readonly IReadOnlyList<AchievementDef> All = new List<AchievementDef>
    {
        // ── Začátky ──────────────────────────────────────────────────────────────
        new("VO2_FIRST_ARTIST",  "První interpret",   "Přidej prvního interpreta",               "bi-music-note-beamed", 10, "Začátky"),
        new("VO2_FIRST_ALBUM",   "První album",       "Přidej první album",                      "bi-vinyl-fill",        10, "Začátky"),
        new("VO2_FIRST_SONG",    "První skladba",     "Přidej první skladbu",                    "bi-music-note",        10, "Začátky"),
        new("VO2_FIRST_EXPORT",  "První export",      "Exportuj data do CSV poprvé",             "bi-download",          10, "Začátky"),
        new("VO2_FIRST_IMPORT",  "První import",      "Importuj skladby z CSV",                  "bi-upload",            15, "Začátky"),
        new("VO2_FIRST_SEARCH",  "Hledání",           "Použij vyhledávání poprvé",               "bi-search",             5, "Začátky"),
        new("VO2_VISIT_HOME",    "Domů",              "Navštiv hlavní dashboard",                "bi-house",              5, "Začátky"),
        new("VO2_VISIT_CHART",   "Graf",              "Zobraz donut chart na dashboardu",        "bi-pie-chart",         10, "Začátky"),
        new("VO2_DARK_MODE",     "Temný mód",         "Přepni na tmavý režim",                   "bi-moon-fill",         10, "Začátky"),
        new("VO2_WELCOME",       "Vítej!",            "Otevři aplikaci poprvé",                  "bi-door-open",          5, "Začátky"),

        // ── Interpreti ───────────────────────────────────────────────────────────
        new("VO2_ARTISTS_5",          "5 interpretů",      "Měj 5 interpretů v databázi",                  "bi-people",            10, "Interpreti"),
        new("VO2_ARTISTS_10",         "10 interpretů",     "Měj 10 interpretů v databázi",                 "bi-people-fill",       15, "Interpreti"),
        new("VO2_ARTISTS_25",         "25 interpretů",     "Měj 25 interpretů v databázi",                 "bi-person-lines-fill", 20, "Interpreti"),
        new("VO2_ARTISTS_50",         "50 interpretů",     "Měj 50 interpretů v databázi",                 "bi-collection",        35, "Interpreti"),
        new("VO2_ARTISTS_100",        "100 interpretů",    "Měj 100 interpretů v databázi",                "bi-trophy",            60, "Interpreti"),
        new("VO2_ARTISTS_500",        "500 interpretů",    "Měj 500 interpretů v databázi",                "bi-trophy-fill",      150, "Interpreti"),
        new("VO2_ARTIST_WITH_ALBUM",  "Diskografie",       "Interpret má aspoň 1 album",                   "bi-vinyl",             10, "Interpreti"),
        new("VO2_ARTIST_5_ALBUMS",    "5 alb",             "Interpret má 5+ alb",                          "bi-vinyl-fill",        25, "Interpreti"),
        new("VO2_ARTIST_10_ALBUMS",   "10 alb",            "Interpret má 10+ alb",                         "bi-collection-fill",   40, "Interpreti"),
        new("VO2_ARTIST_EXPORT",      "Export interpretů", "Exportuj interprety do CSV",                   "bi-filetype-csv",      10, "Interpreti"),
        new("VO2_ARTIST_SEARCH",      "Hledač interpretů", "Hledej interpret podle jména",                 "bi-search",             5, "Interpreti"),
        new("VO2_ARTIST_DELETE",      "Smazání",           "Smaž interpreta",                              "bi-trash",              5, "Interpreti"),
        new("VO2_ARTIST_EDIT",        "Úprava",            "Uprav interpreta",                             "bi-pencil",             5, "Interpreti"),
        new("VO2_ARTIST_BORN",        "Datum narození",    "Přidej interpreta s datem narození",           "bi-calendar-date",     10, "Interpreti"),
        new("VO2_ARTIST_COUNTRY",     "Vlast",             "Přidej interpreta s konkrétní zemí",           "bi-flag",              10, "Interpreti"),
        new("VO2_ARTIST_5_COUNTRIES", "Mezinárodní",       "Měj interprety z 5 různých zemí",              "bi-globe",             25, "Interpreti"),
        new("VO2_ARTIST_MANY_SONGS",  "Prolific",          "Interpret má 50+ skladeb",                     "bi-music-note-list",   40, "Interpreti"),
        new("VO2_ARTIST_LEGEND",      "Legenda",           "Interpret má 100+ skladeb",                    "bi-award",             75, "Interpreti"),
        new("VO2_ARTIST_PAGE_2",      "Listování",         "Přejdi na 2. stránku interpretů",              "bi-chevron-right",      5, "Interpreti"),
        new("VO2_ARTIST_FILTER_10",   "Filtrování",        "Filtruj interprety 10krát",                    "bi-funnel",            10, "Interpreti"),

        // ── Alba ─────────────────────────────────────────────────────────────────
        new("VO2_ALBUMS_5",             "5 alb",              "Měj 5 alb v databázi",                          "bi-vinyl",             10, "Alba"),
        new("VO2_ALBUMS_10",            "10 alb",             "Měj 10 alb v databázi",                         "bi-vinyl-fill",        15, "Alba"),
        new("VO2_ALBUMS_25",            "25 alb",             "Měj 25 alb v databázi",                         "bi-collection",        25, "Alba"),
        new("VO2_ALBUMS_50",            "50 alb",             "Měj 50 alb v databázi",                         "bi-collection-fill",   40, "Alba"),
        new("VO2_ALBUMS_100",           "100 alb",            "Měj 100 alb v databázi",                        "bi-trophy",            70, "Alba"),
        new("VO2_ALBUMS_500",           "500 alb",            "Měj 500 alb v databázi",                        "bi-database",         150, "Alba"),
        new("VO2_ALBUM_10_SONGS",       "Plné album",         "Album má 10+ skladeb",                          "bi-music-note-list",   20, "Alba"),
        new("VO2_ALBUM_EXPORT",         "Export alb",         "Exportuj alba do CSV",                          "bi-filetype-csv",      10, "Alba"),
        new("VO2_ALBUM_SEARCH",         "Hledač alb",         "Hledej album podle názvu",                      "bi-search",             5, "Alba"),
        new("VO2_ALBUM_OLD",            "Historické",         "Přidej album vydané před rokem 1980",           "bi-clock-history",     15, "Alba"),
        new("VO2_ALBUM_NEW",            "Nové",               "Přidej album vydané po roce 2020",              "bi-calendar-check",    10, "Alba"),
        new("VO2_ALBUM_DECADE_60",      "Šedesátky",          "Přidej album z 60. let",                        "bi-vinyl",             20, "Alba"),
        new("VO2_ALBUM_DECADE_70",      "Sedmdesátky",        "Přidej album ze 70. let",                       "bi-vinyl-fill",        20, "Alba"),
        new("VO2_ALBUM_DECADE_80",      "Osmdesátky",         "Přidej album z 80. let",                        "bi-disc",              20, "Alba"),
        new("VO2_ALBUM_DECADE_90",      "Devadesátky",        "Přidej album z 90. let",                        "bi-disc-fill",         20, "Alba"),
        new("VO2_ALBUM_DECADE_00",      "Nultá léta",         "Přidej album z 2000. let",                      "bi-music-player",      15, "Alba"),
        new("VO2_ALBUM_DELETE",         "Smazané album",      "Smaž album",                                    "bi-trash",              5, "Alba"),
        new("VO2_ALBUM_SAME_ARTIST_3",  "Trilogie",           "Interpret má 3 alba",                           "bi-collection",        20, "Alba"),
        new("VO2_ALBUM_PAGE_2",         "Alba strana 2",      "Přejdi na 2. stránku alb",                      "bi-chevron-right",      5, "Alba"),
        new("VO2_ALBUMS_ALL_DECADES",   "Napříč dekádami",    "Měj alba z každé dekády 1970-2020",             "bi-calendar-range",    60, "Alba"),

        // ── Skladby ──────────────────────────────────────────────────────────────
        new("VO2_SONGS_10",            "10 skladeb",         "Měj 10 skladeb v databázi",                     "bi-music-note",        10, "Skladby"),
        new("VO2_SONGS_25",            "25 skladeb",         "Měj 25 skladeb v databázi",                     "bi-music-note-beamed", 15, "Skladby"),
        new("VO2_SONGS_50",            "50 skladeb",         "Měj 50 skladeb v databázi",                     "bi-collection",        25, "Skladby"),
        new("VO2_SONGS_100",           "100 skladeb",        "Měj 100 skladeb v databázi",                    "bi-trophy",            50, "Skladby"),
        new("VO2_SONGS_500",           "500 skladeb",        "Měj 500 skladeb v databázi",                    "bi-database",         100, "Skladby"),
        new("VO2_SONGS_1000",          "Tisíc skladeb!",     "Měj 1000 skladeb v databázi",                   "bi-database-fill",    200, "Skladby"),
        new("VO2_SONGS_5000",          "Pět tisíc!",         "Měj 5000 skladeb v databázi",                   "bi-hdd-fill",         500, "Skladby"),
        new("VO2_SONG_SHORT",          "Krátká",             "Přidej skladbu kratší než 2 minuty (120s)",     "bi-skip-forward",      10, "Skladby"),
        new("VO2_SONG_LONG",           "Epická",             "Přidej skladbu delší než 10 minut (600s)",      "bi-hourglass",         20, "Skladby"),
        new("VO2_SONG_EXPORT",         "Export skladeb",     "Exportuj skladby do CSV",                       "bi-filetype-csv",      10, "Skladby"),
        new("VO2_SONG_IMPORT",         "Import skladeb",     "Importuj skladby z CSV",                        "bi-file-earmark-arrow-up", 15, "Skladby"),
        new("VO2_SONG_IMPORT_100",     "Velký import",       "Importuj 100+ skladeb naráz",                   "bi-cloud-upload",      40, "Skladby"),
        new("VO2_SONG_SEARCH",         "Hledač skladeb",     "Hledej skladbu",                                "bi-search",             5, "Skladby"),
        new("VO2_SONG_YEAR_OLD",       "Stará klasika",      "Přidej skladbu vydanou před rokem 1970",        "bi-clock-history",     20, "Skladby"),
        new("VO2_SONG_2020",           "Nový hit",           "Přidej skladbu z roku 2020+",                   "bi-lightning",         10, "Skladby"),
        new("VO2_SONG_DELETE",         "Smazání",            "Smaž skladbu",                                  "bi-trash",              5, "Skladby"),
        new("VO2_SONG_EDIT",           "Úprava",             "Uprav skladbu",                                 "bi-pencil",             5, "Skladby"),
        new("VO2_SONG_PAGE_3",         "Listovač",           "Přejdi na 3. stránku skladeb",                  "bi-skip-end",          10, "Skladby"),
        new("VO2_SONG_FILTER_YEAR",    "Filtr roku",         "Filtruj skladby podle roku vydání",             "bi-calendar2",          5, "Skladby"),
        new("VO2_SONG_SAME_ARTIST_10", "Oblíbenec",          "Měj 10 skladeb stejného interpreta",            "bi-heart",             20, "Skladby"),
        new("VO2_SONG_DURATION_AVG",   "Průměr délky",       "Průměrná délka skladeb překročí 3 minuty",      "bi-stopwatch",         15, "Skladby"),
        new("VO2_SONG_NO_ALBUM",       "Singl",              "Přidej skladbu bez alba",                       "bi-music-note-beamed", 10, "Skladby"),
        new("VO2_SONG_WITH_ALBUM",     "Albová",             "Přidej skladbu přiřazenou k albu",              "bi-vinyl",             10, "Skladby"),
        new("VO2_PERFECT_IMPORT",      "Čistý import",       "Importuj CSV bez jediné chyby",                 "bi-check-all",         25, "Skladby"),
        new("VO2_SONGS_ALL_DECADES",   "Časová osa",         "Měj skladby z každé dekády 1960-2020",          "bi-calendar-range",    75, "Skladby"),

        // ── Speciální ────────────────────────────────────────────────────────────
        new("VO2_STATS_CARD_ARTISTS", "Statistika interpretů", "Zobraz počet interpretů na dashboardu",   "bi-card-text",          5, "Speciální"),
        new("VO2_STATS_CARD_ALBUMS",  "Statistika alb",        "Zobraz počet alb na dashboardu",          "bi-vinyl",              5, "Speciální"),
        new("VO2_STATS_CARD_SONGS",   "Statistika skladeb",    "Zobraz počet skladeb na dashboardu",      "bi-music-note",         5, "Speciální"),
        new("VO2_DONUT_CHART",        "Donut graf",            "Zobraz donut chart na dashboardu",        "bi-pie-chart-fill",    10, "Speciální"),
        new("VO2_EXPORT_ALL",         "Exportuj vše",          "Exportuj interprety, alba i skladby",     "bi-download",          30, "Speciální"),
        new("VO2_IMPORT_ALL",         "Importuj vše",          "Importuj interprety i skladby",           "bi-upload",            30, "Speciální"),
        new("VO2_SEARCH_ALL",         "Hledej všude",          "Použij vyhledávání na všech stránkách",   "bi-search",            20, "Speciální"),
        new("VO2_NIGHT_OWL",          "Noční muzikant",        "Použij aplikaci po půlnoci",              "bi-moon-stars",        15, "Speciální"),
        new("VO2_MORNING_BIRD",       "Ranní muzikant",        "Použij aplikaci před 7. hodinou",         "bi-sunrise",           15, "Speciální"),
        new("VO2_50_ACHIEVEMENTS",    "Sběratel",              "Odemkni 50 achievementů",                 "bi-collection-fill",  200, "Speciální"),
        new("VO2_1000_POINTS",        "Tisíc bodů",            "Získej 1000 bodů",                        "bi-1-circle-fill",    150, "Speciální"),
        new("VO2_LIGHT_MODE",         "Světlý mód",            "Přepni na světlý režim",                  "bi-sun-fill",          10, "Speciální"),
        new("VO2_USE_FILTER",         "Filtrovač",             "Filtruj data alespoň 5krát",              "bi-funnel",            10, "Speciální"),
        new("VO2_PAGINATION",         "Navigátor",             "Listuj stránkami 5krát",                  "bi-chevron-right",     10, "Speciální"),
        new("VO2_ALL_PAGES",          "Průzkumník",            "Navštiv všechny 4 hlavní stránky",        "bi-map",               25, "Speciální"),
        new("VO2_DATA_RICH",          "Bohatá databáze",       "Měj 100+ interpretů, 500+ skladeb",       "bi-database-fill",     75, "Speciální"),
        new("VO2_CONSISTENT_USE",     "Pravidelný posluchač",  "Otevři aplikaci 7 dní po sobě",           "bi-calendar-week",     50, "Speciální"),
        new("VO2_BULK_DATA",          "Velká data",            "Měj 10000+ skladeb celkem",               "bi-hdd-network",      300, "Speciální"),
        new("VO2_EXPORT_HUGE",        "Mega export",           "Exportuj 1000+ skladeb naráz",            "bi-file-earmark-zip",  50, "Speciální"),
        new("VO2_SPEED_ADDER",        "Rychlý přidávač",       "Přidej 10 skladeb za 10 minut",           "bi-stopwatch-fill",    30, "Speciální"),
        new("VO2_COMPLETE_ARTIST",    "Kompletní profil",      "Interpret má jméno, zemi i datum narozenin", "bi-person-check",  15, "Speciální"),
        new("VO2_COMPLETE_ALBUM",     "Kompletní album",       "Album má název, rok i interpret",         "bi-vinyl-fill",        15, "Speciální"),
        new("VO2_COMPLETE_SONG",      "Kompletní skladba",     "Skladba má název, rok i délku",           "bi-music-note-beamed", 15, "Speciální"),
        new("VO2_POWER_USER",         "Power user",            "Použij export, import i vyhledávání",     "bi-tools",             50, "Speciální"),
        new("VO2_COMPLETE_ALL",       "Hudební maestro",       "Odemkni 90% achievementů",                "bi-award-fill",       500, "Speciální"),
    };
}
